name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      run: msbuild -t:restore

    - name: Build project
      run: msbuild "OculusKiller\OculusKiller.csproj" /p:Configuration=Release /p:Platform=x64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Build Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_ACTIONS }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: OculusKiller\OculusKiller\bin\x64\Release\OculusDash.exe
        asset_name: OculusDash.exe
        asset_content_type: application/vnd.microsoft.portable-executable
